<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
<title>TestNG Report</title>
<style type="text/css">table {margin-bottom:10px;border-collapse:collapse;empty-cells:show}th,td {border:1px solid #009;padding:.25em .5em}th {vertical-align:bottom}td {vertical-align:top}table a {font-weight:bold}.stripe td {background-color: #E6EBF9}.num {text-align:right}.passedodd td {background-color: #3F3}.passedeven td {background-color: #0A0}.skippedodd td {background-color: #DDD}.skippedeven td {background-color: #CCC}.failedodd td,.attn {background-color: #F33}.failedeven td,.stripe .attn {background-color: #D00}.stacktrace {white-space:pre;font-family:monospace}.totop {font-size:85%;text-align:center;border-bottom:2px solid #000}.invisible {display:none}</style>
</head>
<body>
<table>
<tr><th>Test</th><th># Passed</th><th># Skipped</th><th># Failed</th><th>Time (ms)</th><th>Included Groups</th><th>Excluded Groups</th></tr>
<tr><th colspan="7">Retry Failed Test Suite</th></tr>
<tr><td><a href="#t0">Retry Multiple Fail Test Cases</a></td><td class="num">1</td><td class="num attn">6</td><td class="num attn">2</td><td class="num">32</td><td></td><td></td></tr>
</table>
<table id='summary'><thead><tr><th>Class</th><th>Method</th><th>Start</th><th>Time (ms)</th></tr></thead><tbody><tr><th colspan="4">Retry Failed Test Suite</th></tr></tbody><tbody id="t0"><tr><th colspan="4">Retry Multiple Fail Test Cases &#8212; failed</th></tr><tr class="failedeven"><td rowspan="2">com.wa.qa.testcases.RetryTestClass</td><td><a href="#m0">testA</a></td><td rowspan="1">1601543917611</td><td rowspan="1">0</td></tr><tr class="failedeven"><td><a href="#m1">testB</a></td><td rowspan="1">1601543917617</td><td rowspan="1">0</td></tr><tr><th colspan="4">Retry Multiple Fail Test Cases &#8212; skipped</th></tr><tr class="skippedeven"><td rowspan="6">com.wa.qa.testcases.RetryTestClass</td><td><a href="#m2">testA</a></td><td rowspan="3">1601543917604</td><td rowspan="3">5</td></tr><tr class="skippedeven"><td><a href="#m3">testA</a></td></tr><tr class="skippedeven"><td><a href="#m4">testA</a></td></tr><tr class="skippedeven"><td><a href="#m5">testB</a></td><td rowspan="3">1601543917616</td><td rowspan="3">1</td></tr><tr class="skippedeven"><td><a href="#m6">testB</a></td></tr><tr class="skippedeven"><td><a href="#m7">testB</a></td></tr><tr><th colspan="4">Retry Multiple Fail Test Cases &#8212; passed</th></tr><tr class="passedeven"><td rowspan="1">com.wa.qa.testcases.RetryTestClass</td><td><a href="#m8">testC</a></td><td rowspan="1">1601543917617</td><td rowspan="1">0</td></tr></tbody>
</table>
<h2>Retry Multiple Fail Test Cases</h2><h3 id="m0">com.wa.qa.testcases.RetryTestClass#testA</h3><table class="result"><tr><th>Exception</th></tr><tr><td><div class="stacktrace">java.lang.AssertionError: expected [b] but found [a]
	at com.wa.qa.testcases.RetryTestClass.testA(RetryTestClass.java:11)
... Removed 34 stack frames</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p>
<h3 id="m1">com.wa.qa.testcases.RetryTestClass#testB</h3><table class="result"><tr><th>Exception</th></tr><tr><td><div class="stacktrace">java.lang.AssertionError: expected [a] but found [A]
	at com.wa.qa.testcases.RetryTestClass.testB(RetryTestClass.java:16)
... Removed 34 stack frames</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p>
<h3 id="m2">com.wa.qa.testcases.RetryTestClass#testA</h3><table class="result"><tr><th>Exception</th></tr><tr><td><div class="stacktrace">java.lang.AssertionError: expected [b] but found [a]
	at com.wa.qa.testcases.RetryTestClass.testA(RetryTestClass.java:11)
... Removed 34 stack frames</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p>
<h3 id="m3">com.wa.qa.testcases.RetryTestClass#testA</h3><table class="result"><tr><th>Exception</th></tr><tr><td><div class="stacktrace">java.lang.AssertionError: expected [b] but found [a]
	at com.wa.qa.testcases.RetryTestClass.testA(RetryTestClass.java:11)
... Removed 34 stack frames</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p>
<h3 id="m4">com.wa.qa.testcases.RetryTestClass#testA</h3><table class="result"><tr><th>Exception</th></tr><tr><td><div class="stacktrace">java.lang.AssertionError: expected [b] but found [a]
	at com.wa.qa.testcases.RetryTestClass.testA(RetryTestClass.java:11)
... Removed 34 stack frames</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p>
<h3 id="m5">com.wa.qa.testcases.RetryTestClass#testB</h3><table class="result"><tr><th>Exception</th></tr><tr><td><div class="stacktrace">java.lang.AssertionError: expected [a] but found [A]
	at com.wa.qa.testcases.RetryTestClass.testB(RetryTestClass.java:16)
... Removed 34 stack frames</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p>
<h3 id="m6">com.wa.qa.testcases.RetryTestClass#testB</h3><table class="result"><tr><th>Exception</th></tr><tr><td><div class="stacktrace">java.lang.AssertionError: expected [a] but found [A]
	at com.wa.qa.testcases.RetryTestClass.testB(RetryTestClass.java:16)
... Removed 34 stack frames</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p>
<h3 id="m7">com.wa.qa.testcases.RetryTestClass#testB</h3><table class="result"><tr><th>Exception</th></tr><tr><td><div class="stacktrace">java.lang.AssertionError: expected [a] but found [A]
	at com.wa.qa.testcases.RetryTestClass.testB(RetryTestClass.java:16)
... Removed 34 stack frames</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p>
<h3 id="m8">com.wa.qa.testcases.RetryTestClass#testC</h3><table class="result"><tr><th class="invisible"/></tr></table><p class="totop"><a href="#summary">back to summary</a></p>
</body>
</html>
